"""Fetches GTS Root R1–R4 from pki.goog, validates them, and writes google_root_cas.h.

Usage:
    python tools/make_ca_header.py

Requirements:
    pip install cryptography requests
"""
from __future__ import annotations

import hashlib
import sys
import textwrap
from datetime import datetime, timezone
from pathlib import Path

try:
    import requests
    from cryptography import x509
    from cryptography.hazmat.primitives import hashes, serialization
except ImportError:
    print("ERROR: Install dependencies first:  pip install cryptography requests", file=sys.stderr)
    sys.exit(1)

ROOT_URLS = [
    "https://pki.goog/repo/certs/gtsr1.pem",
    "https://pki.goog/repo/certs/gtsr2.pem",
    "https://pki.goog/repo/certs/gtsr3.pem",
    "https://pki.goog/repo/certs/gtsr4.pem",
]

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
HEADER_PATH = PROJECT_DIR / "google_root_cas.h"
PEM_BUNDLE_PATH = SCRIPT_DIR / "google_roots.pem"


def fetch_and_validate(url: str) -> tuple[x509.Certificate, str, str]:
    """Download a PEM, parse it, validate it's a self-signed CA, return (cert, pem_text, sha256_fp)."""
    print(f"  Fetching {url} ... ", end="", flush=True)
    resp = requests.get(url, timeout=30)
    if resp.status_code == 404:
        print("404 NOT FOUND")
        print(f"ERROR: {url} returned 404. Check https://pki.goog/repository/ for current links.",
              file=sys.stderr)
        sys.exit(1)
    resp.raise_for_status()
    pem_text = resp.text.strip()
    cert = x509.load_pem_x509_certificate(pem_text.encode("ascii"))

    # Validate: must be a CA
    try:
        basic = cert.extensions.get_extension_for_class(x509.BasicConstraints)
        assert basic.value.ca, "Not a CA certificate"
    except x509.ExtensionNotFound:
        print("FAILED — no BasicConstraints")
        sys.exit(1)

    # Validate: must be self-signed (issuer == subject)
    if cert.issuer != cert.subject:
        print("FAILED — not self-signed")
        sys.exit(1)

    # Validate: must not be expired
    now = datetime.now(timezone.utc)
    if cert.not_valid_after_utc < now:
        print(f"FAILED — expired on {cert.not_valid_after_utc.isoformat()}")
        sys.exit(1)

    # SHA-256 fingerprint
    fp = cert.fingerprint(hashes.SHA256()).hex(":").upper()

    print(f"OK  (expires {cert.not_valid_after_utc.date()})")
    print(f"    Subject: {cert.subject.rfc4514_string()}")
    print(f"    SHA-256: {fp}")

    return cert, pem_text, fp


def pem_to_c_literal(pem_text: str) -> str:
    """Convert a PEM string to a C string literal with proper escaping."""
    lines = []
    for line in pem_text.strip().splitlines():
        lines.append(f'"{line}\\n"')
    return "\n".join(lines)


def main():
    print("=" * 60)
    print("Google Trust Services Root CA Bundle Generator")
    print("=" * 60)

    certs_info: list[tuple[str, str, str]] = []  # (subject_cn, fp, pem_text)
    all_pem = []

    for url in ROOT_URLS:
        cert, pem_text, fp = fetch_and_validate(url)
        # Extract CN from subject
        cn = "unknown"
        for attr in cert.subject:
            if attr.oid == x509.oid.NameOID.COMMON_NAME:
                cn = attr.value
                break
        certs_info.append((cn, fp, pem_text))
        all_pem.append(pem_text)

    print()
    print(f"Writing {HEADER_PATH} ...")

    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    header_lines = [
        "#pragma once",
        f"// AUTO-GENERATED by tools/make_ca_header.py on {now_str}. Do not edit by hand.",
        "// Source: https://pki.goog/repo/certs/gtsr{1..4}.pem",
        "// SHA-256 fingerprints (verify against https://pki.goog/repository/):",
    ]
    for cn, fp, _ in certs_info:
        header_lines.append(f"//   {cn}: {fp}")
    header_lines.append("")
    header_lines.append("static const char GOOGLE_ROOT_CAS[] PROGMEM =")

    c_parts = []
    for i, (cn, fp, pem_text) in enumerate(certs_info):
        c_parts.append(f"// --- {cn} ---")
        c_parts.append(pem_to_c_literal(pem_text))

    header_lines.append("\n".join(c_parts) + ";")
    header_lines.append("")

    HEADER_PATH.write_text("\n".join(header_lines), encoding="utf-8")
    print(f"  ✓ Written ({len(certs_info)} certificates)")

    print(f"Writing {PEM_BUNDLE_PATH} ...")
    PEM_BUNDLE_PATH.write_text("\n".join(all_pem) + "\n", encoding="utf-8")
    print(f"  ✓ Written")

    print()
    print("=" * 60)
    print("DONE. Fingerprints to verify against https://pki.goog/repository/:")
    for cn, fp, _ in certs_info:
        print(f"  {cn}: {fp}")
    print("=" * 60)


if __name__ == "__main__":
    main()
